/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author chave
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmDoctor
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dspEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        itemPacientes = new javax.swing.JMenuItem();
        itemEspecialidades = new javax.swing.JMenuItem();
        itemDoctores = new javax.swing.JMenuItem();
        itemHistoriasClinicas = new javax.swing.JMenuItem();
        itemAtencionesDelDia = new javax.swing.JMenuItem();
        itemAtencionesPorFecha = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POSTA MEDICA BIOVITAL");
        setBackground(new java.awt.Color(102, 204, 255));
        setBounds(new java.awt.Rectangle(0, 0, 700, 600));

        dspEscritorio.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout dspEscritorioLayout = new javax.swing.GroupLayout(dspEscritorio);
        dspEscritorio.setLayout(dspEscritorioLayout);
        dspEscritorioLayout.setHorizontalGroup(
            dspEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        dspEscritorioLayout.setVerticalGroup(
            dspEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Menu.png"))); // NOI18N
        Menu.setText("MENU PRINCIPAL");

        itemPacientes.setText("Pacientes");
        Menu.add(itemPacientes);

        itemEspecialidades.setText("Especialidades");
        itemEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEspecialidadesActionPerformed(evt);
            }
        });
        Menu.add(itemEspecialidades);

        itemDoctores.setText("Doctores");
        Menu.add(itemDoctores);

        itemHistoriasClinicas.setText("Historias Clinicas");
        itemHistoriasClinicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHistoriasClinicasActionPerformed(evt);
            }
        });
        Menu.add(itemHistoriasClinicas);

        itemAtencionesDelDia.setText("Atenciones del dia");
        itemAtencionesDelDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAtencionesDelDiaActionPerformed(evt);
            }
        });
        Menu.add(itemAtencionesDelDia);

        itemAtencionesPorFecha.setText("Atenciones por fecha");
        Menu.add(itemAtencionesPorFecha);

        jMenuBar1.add(Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dspEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dspEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAtencionesDelDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAtencionesDelDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAtencionesDelDiaActionPerformed

    private void itemEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEspecialidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEspecialidadesActionPerformed

    private void itemHistoriasClinicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHistoriasClinicasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemHistoriasClinicasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    public javax.swing.JDesktopPane dspEscritorio;
    public javax.swing.JMenuItem itemAtencionesDelDia;
    public javax.swing.JMenuItem itemAtencionesPorFecha;
    public javax.swing.JMenuItem itemDoctores;
    public javax.swing.JMenuItem itemEspecialidades;
    public javax.swing.JMenuItem itemHistoriasClinicas;
    public javax.swing.JMenuItem itemPacientes;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
