/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class FrmPaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pacientes
     */
    public FrmPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGenero = new javax.swing.ButtonGroup();
        bgEstado = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jrbBajo = new javax.swing.JRadioButton();
        txtTelefono = new javax.swing.JTextField();
        jrbAlto = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jrbVaron = new javax.swing.JRadioButton();
        jrbMujer = new javax.swing.JRadioButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        txtPrimerApellido = new javax.swing.JTextField();
        txtNacimiento = new javax.swing.JTextField();
        txtNumHistClinica = new javax.swing.JTextField();
        txtSegundoApellido = new javax.swing.JTextField();
        btnGrupoSanguineo = new javax.swing.JComboBox<>();
        txtNombres = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtLocalidad = new javax.swing.JTextField();
        cbxEstadoCivil = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnOrdenar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        setClosable(true);
        setTitle("Pacientes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("REGISTRO DE PACIENTES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(jLabel4)
                .addContainerGap(500, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 70));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Estado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jrbBajo.setBackground(new java.awt.Color(153, 204, 255));
        bgEstado.add(jrbBajo);
        jrbBajo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrbBajo.setForeground(new java.awt.Color(255, 255, 255));
        jrbBajo.setText("Bajo");
        jPanel1.add(jrbBajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        txtTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Teléfono"));
        txtTelefono.addActionListener(this::txtTelefonoActionPerformed);
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 210, 50));

        jrbAlto.setBackground(new java.awt.Color(153, 204, 255));
        bgEstado.add(jrbAlto);
        jrbAlto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrbAlto.setForeground(new java.awt.Color(255, 255, 255));
        jrbAlto.setText("Alto");
        jPanel1.add(jrbAlto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Género");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jrbVaron.setBackground(new java.awt.Color(153, 204, 255));
        bgGenero.add(jrbVaron);
        jrbVaron.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrbVaron.setForeground(new java.awt.Color(255, 255, 255));
        jrbVaron.setText("Varón");
        jPanel1.add(jrbVaron, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jrbMujer.setBackground(new java.awt.Color(153, 204, 255));
        bgGenero.add(jrbMujer);
        jrbMujer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrbMujer.setForeground(new java.awt.Color(255, 255, 255));
        jrbMujer.setText("Mujer");
        jPanel1.add(jrbMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(51, 102, 255));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setToolTipText("");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 120, 30));

        btnGuardar.setBackground(new java.awt.Color(51, 102, 255));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setToolTipText("");
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        btnConsultar.setBackground(new java.awt.Color(51, 102, 255));
        btnConsultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConsultar.setText("CONSULTAR");
        btnConsultar.setToolTipText("");
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 120, 30));

        txtPrimerApellido.setBorder(javax.swing.BorderFactory.createTitledBorder("Primer Apellido"));
        jPanel1.add(txtPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 210, 50));

        txtNacimiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Nacimiento"));
        jPanel1.add(txtNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 210, 50));

        txtNumHistClinica.setBorder(javax.swing.BorderFactory.createTitledBorder("N° Hist Clinica"));
        jPanel1.add(txtNumHistClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 150, 50));

        txtSegundoApellido.setBorder(javax.swing.BorderFactory.createTitledBorder("Segundo Apellido"));
        jPanel1.add(txtSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 210, 50));

        btnGrupoSanguineo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "O+", "B+", "AB+", "A-", "O-", "B-", "AB-" }));
        btnGrupoSanguineo.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupo Sanguíneo"));
        btnGrupoSanguineo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGrupoSanguineo.addActionListener(this::btnGrupoSanguineoActionPerformed);
        jPanel1.add(btnGrupoSanguineo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 140, 50));

        txtNombres.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombres"));
        txtNombres.addActionListener(this::txtNombresActionPerformed);
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 210, 50));

        txtDNI.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI | NIF"));
        jPanel1.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 210, 50));

        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        txtEmail.addActionListener(this::txtEmailActionPerformed);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 190, 50));

        txtDireccion.setBorder(javax.swing.BorderFactory.createTitledBorder("Dirección"));
        txtDireccion.addActionListener(this::txtDireccionActionPerformed);
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 380, 50));

        txtLocalidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Localidad"));
        txtLocalidad.addActionListener(this::txtLocalidadActionPerformed);
        jPanel1.add(txtLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, 230, 50));

        cbxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOLTERO", "CASADO", "CONVIVIENTE", "DIVORSIADO", "VIUDO" }));
        cbxEstadoCivil.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado Civil"));
        cbxEstadoCivil.addActionListener(this::cbxEstadoCivilActionPerformed);
        jPanel1.add(cbxEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 110, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 353, 1140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("LISTA DE PACIENTES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 20));

        btnOrdenar.setBackground(new java.awt.Color(51, 102, 255));
        btnOrdenar.setText("ORDENAR POR APELLIDO");
        btnOrdenar.addActionListener(this::btnOrdenarActionPerformed);
        jPanel1.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(913, 363, 200, 30));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N° Historia Clinica", "DNI", "Nombres Completos", "Télefono"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 1110, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1140, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstadoCivilActionPerformed

    private void btnGrupoSanguineoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupoSanguineoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrupoSanguineoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalidadActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEstado;
    public javax.swing.ButtonGroup bgGenero;
    public javax.swing.JButton btnConsultar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JComboBox<String> btnGrupoSanguineo;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnOrdenar;
    public javax.swing.JComboBox<String> cbxEstadoCivil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JRadioButton jrbAlto;
    public javax.swing.JRadioButton jrbBajo;
    public javax.swing.JRadioButton jrbMujer;
    public javax.swing.JRadioButton jrbVaron;
    public javax.swing.JTable tblDatos;
    public javax.swing.JTextField txtDNI;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtLocalidad;
    public javax.swing.JTextField txtNacimiento;
    public javax.swing.JTextField txtNombres;
    public javax.swing.JTextField txtNumHistClinica;
    public javax.swing.JTextField txtPrimerApellido;
    public javax.swing.JTextField txtSegundoApellido;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
